apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: madhupdevops/backend-wanderlust:v1
          env:
            - name: MONGODB_URI
              value: mongodb://admin:admin@mongo-service:27017/wanderlust
          ports:
            - containerPort: 5000
