apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: madhupdevops/frontend-wanderlust:v1
          env:
            - name: VITE_API_PATH
              value: "http://localhost:5000"
          ports:
            - containerPort: 5173
